name: Rust

on:
  push:
    paths-ignore: 
      - 'README.md'
      - '.github/**'
    branches: [ master ]
    
  pull_request:
    paths-ignore: 
      - 'README.md'
      - '.github/**'
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: sudo apt update
    - run: sudo apt install -y libasound2-dev libavcodec-dev libavformat-dev libswresample-dev libavutil-dev
    - run: cargo build --release
