name: Rust

on:
  push:
    paths-ignore: 
      - 'README.md'
      - '.github/**'
    branches: [ master ]
    
  pull_request:
    paths-ignore: 
      - 'README.md'
      - '.github/**'
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-latest]
        include:
          - name: linux
            os: ubuntu-18.04
            artifact_name: target/release/RustPlayer
          - name: macos
            os: macos-latest
            artifact_name: target/release/RustPlayer
          - name: windows
            os: windows-latest
            artifact_name: target/release/RustPlayer.exe
            asset_name: RustPlayer-windows.exe
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install deps for linux
      if: matrix.os == 'ubuntu-18.04'
      run: sudo apt update && sudo apt install -y libasound2-dev libavcodec-dev libavformat-dev libswresample-dev libavutil-dev libavformat-dev pkg-config
    - name: Install vcpkg for windows
      if: matrix.os == 'windows-latest'
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: e809a42f87565e803b2178a0c11263f462d1800a
    - name: Install ffmpeg deps for windows
      if: matrix.os == 'windows-latest'
      run: ${VCPKG_ROOT}/vcpkg install llvm:x64-windows ffmpeg:x64-windows-static-md
    - name: install ffmpeg deps for macOS
      if: matrix.os == 'macos-latest'
      run: brew install ffmpeg@4 pkg-config && brew link ffmpeg@4
    - run: cargo build --release
