name: Rust

on:
  push:
    paths-ignore: 
      - 'README.md'
      - '.github/**'
    branches: [ master ]
    
  pull_request:
    paths-ignore: 
      - 'README.md'
      - '.github/**'
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest]
        include:
          - name: linux
            os: ubuntu-18.04
            artifact_name: target/release/RustPlayer
          - name: macos
            os: macos-latest
            artifact_name: target/release/RustPlayer
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - if: ${{ matrix.os }} == "ubuntu-18.04"
      run: sudo apt update
    - if: ${{ matrix.os }} == "ubuntu-18.04"
      run: sudo apt install -y libasound2-dev libavcodec-dev libavformat-dev libswresample-dev libavutil-dev libavformat-dev
    - if: ${{ matrix.os }} == "macos-latest"
      run: brew install ffmpeg@4 && brew link ffmpeg@4
    - run: cargo build --release
