name: Rust

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths-ignore: 
      - 'README.md'
      - '.github/**'
    branches: [ master ]
    
  pull_request:
    paths-ignore: 
      - 'README.md'
      - '.github/**'
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  VCPKG_COMMIT_ID: 94ce0dab56f4d8ba6bd631ba59ed682b02d45c46
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-latest] 
        include:
          - name: linux
            os: ubuntu-20.04
            artifact_name: target/release/RustPlayer
            asset_name: RustPlayer-linux-amd64
          - name: macos
            os: macos-latest
            artifact_name: target/release/RustPlayer
            asset_name: RustPlayer-macos
    steps:
    - uses: actions/checkout@v2
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2

    - name: install deps for linux
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt update && sudo apt install -y libasound2-dev libavcodec-dev libavformat-dev libswresample-dev libavutil-dev libavformat-dev pkg-config
        
    - name: install ffmpeg deps for macOS
      if: matrix.os == 'macos-latest'
      run: brew install ffmpeg@4 pkg-config && brew link ffmpeg@4

    - name: Install cargo bundle
      run: cargo install cargo-bundle

    - name: build RustPlayer
      run: cargo bundle

    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}

  build-on-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64, artifact_name: target/release/RustPlayer.exe , asset_name: RustPlayer-windows-x86_64.exe }
          # - { sys: mingw32, env: i686, artifact_name: target/release/RustPlayer.exe , asset_name: RustPlayer-windows-x86.exe }
          # - { sys: ucrt64,  env: ucrt-x86_64 }  # Experimental!
          # - { sys: clang64, env: clang-x86_64 } # Experimental!
    # defaults:
    #   run:
    #     shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2

    - name: setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

    - name: Install ffmpeg static
      run: |
          $VCPKG_ROOT/vcpkg install ffmpeg:x64-windows-static-md
      shell: bash

    - name: build RustPlayer
      run: |
        cargo build --release

    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}

